<?php

namespace Database\Seeders;

use App\Models\Mesin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MesinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Matikan pengecekan foreign key
        Schema::disableForeignKeyConstraints();

        // 2. Kosongkan tabel mesins
        DB::table('mesins')->truncate();

        $mesins = [
            // PLANT A
            ['nama_mesin' => 'HD-10C', 'plant' => 'A'],
            ['nama_mesin' => 'TW-RBD-CU', 'plant' => 'A'],
            ['nama_mesin' => 'MD-1', 'plant' => 'A'],
            ['nama_mesin' => 'MULTI DRAWING-1', 'plant' => 'A'],
            ['nama_mesin' => 'MULTI DRAWING-2', 'plant' => 'A'],
            ['nama_mesin' => 'MULTI DRAWING-3', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp1', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp2', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp3', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp4', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp5', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp6', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp7', 'plant' => 'A'],
            ['nama_mesin' => 'BC-Samp8', 'plant' => 'A'],
            ['nama_mesin' => 'BC-5', 'plant' => 'A'],
            ['nama_mesin' => 'BC-6', 'plant' => 'A'],
            ['nama_mesin' => 'AW-1', 'plant' => 'A'],
            ['nama_mesin' => 'AW-2', 'plant' => 'A'],
            ['nama_mesin' => 'EX-70+40', 'plant' => 'A'],
            ['nama_mesin' => 'EX-60A', 'plant' => 'A'],
            ['nama_mesin' => 'EX-60B', 'plant' => 'A'],
            ['nama_mesin' => 'EX-80+60', 'plant' => 'A'],
            ['nama_mesin' => 'EX-80H', 'plant' => 'A'],
            ['nama_mesin' => 'EX-80G', 'plant' => 'A'],
            ['nama_mesin' => 'CB-4C', 'plant' => 'A'],
            ['nama_mesin' => 'CB-7E', 'plant' => 'A'],
            ['nama_mesin' => 'TW-125C', 'plant' => 'A'],
            ['nama_mesin' => 'ST-7F', 'plant' => 'A'],
            ['nama_mesin' => 'EX-70A', 'plant' => 'A'],
            ['nama_mesin' => 'CB-16B', 'plant' => 'A'],
            ['nama_mesin' => 'CB-48A', 'plant' => 'A'],
            ['nama_mesin' => 'ST-30A', 'plant' => 'A'],
            ['nama_mesin' => 'ST-66', 'plant' => 'A'],
            ['nama_mesin' => 'REW-30A', 'plant' => 'A'],
            ['nama_mesin' => 'REW-67', 'plant' => 'A'],
            ['nama_mesin' => 'REW-8A', 'plant' => 'A'],
            ['nama_mesin' => 'EX-90+80', 'plant' => 'A'],
            ['nama_mesin' => 'EX-90F', 'plant' => 'A'],
            ['nama_mesin' => 'EX-90D', 'plant' => 'A'],
            ['nama_mesin' => 'EX-90K', 'plant' => 'A'],
            ['nama_mesin' => 'EX-120D', 'plant' => 'A'],
            ['nama_mesin' => 'EX-120+70', 'plant' => 'A'],
            ['nama_mesin' => 'CB-1F', 'plant' => 'A'],
            ['nama_mesin' => 'CL-1', 'plant' => 'A'],
            ['nama_mesin' => 'CL-2', 'plant' => 'A'],
            ['nama_mesin' => 'CL-3', 'plant' => 'A'],
            ['nama_mesin' => 'CL-4', 'plant' => 'A'],
            ['nama_mesin' => 'CL-5', 'plant' => 'A'],
            ['nama_mesin' => 'CL-6', 'plant' => 'A'],
            ['nama_mesin' => 'CL-7', 'plant' => 'A'],
            ['nama_mesin' => 'CL-8', 'plant' => 'A'],
            ['nama_mesin' => 'MC-1', 'plant' => 'A'],
            ['nama_mesin' => 'MC-2', 'plant' => 'A'],
            ['nama_mesin' => 'MC-3', 'plant' => 'A'],
            ['nama_mesin' => 'REW-AR-21', 'plant' => 'A'],
            ['nama_mesin' => 'AR-21', 'plant' => 'A'],
            ['nama_mesin' => 'REW-AR-72B-1', 'plant' => 'A'],
            ['nama_mesin' => 'REW-AR-72B-2', 'plant' => 'A'],
            ['nama_mesin' => 'AR-72B', 'plant' => 'A'],
            ['nama_mesin' => 'Heli 2,5 Ton', 'plant' => 'A'],
            ['nama_mesin' => 'Heli 5 Ton', 'plant' => 'A'],
            ['nama_mesin' => 'Heli 1,8 Ton', 'plant' => 'A'],

            // PLANT B
            ['nama_mesin' => 'RBD-AL', 'plant' => 'B'],
            ['nama_mesin' => 'HD-10A', 'plant' => 'B'],
            ['nama_mesin' => 'HD-8C', 'plant' => 'B'],
            ['nama_mesin' => 'HD-8E', 'plant' => 'B'],
            ['nama_mesin' => 'MD-5', 'plant' => 'B'],
            ['nama_mesin' => 'MD-6', 'plant' => 'B'],
            ['nama_mesin' => 'MD-7', 'plant' => 'B'],
            ['nama_mesin' => 'OVEN', 'plant' => 'B'],
            ['nama_mesin' => 'ST-7H', 'plant' => 'B'],
            ['nama_mesin' => 'ST-7I', 'plant' => 'B'],
            ['nama_mesin' => 'ST-6B', 'plant' => 'B'],
            ['nama_mesin' => 'ST-7D', 'plant' => 'B'],
            ['nama_mesin' => 'ST-7A', 'plant' => 'B'],
            ['nama_mesin' => 'ST-7J', 'plant' => 'B'],
            ['nama_mesin' => 'ST-12B', 'plant' => 'B'],
            ['nama_mesin' => 'ST-19C', 'plant' => 'B'],
            ['nama_mesin' => 'ST-30B', 'plant' => 'B'],
            ['nama_mesin' => 'ST-54A', 'plant' => 'B'],
            ['nama_mesin' => 'ST-54C', 'plant' => 'B'],
            ['nama_mesin' => 'ST-54E', 'plant' => 'B'],
            ['nama_mesin' => 'EX-90B', 'plant' => 'B'],
            ['nama_mesin' => 'EX-100B', 'plant' => 'B'],
            ['nama_mesin' => 'CB-2B', 'plant' => 'B'],
            ['nama_mesin' => 'CB-2C', 'plant' => 'B'],
            ['nama_mesin' => 'CB-4B', 'plant' => 'B'],
            ['nama_mesin' => 'REW-1', 'plant' => 'B'],
            ['nama_mesin' => 'REW-2', 'plant' => 'B'],
            ['nama_mesin' => 'REW-3', 'plant' => 'B'],
            ['nama_mesin' => 'REW-4', 'plant' => 'B'],
            ['nama_mesin' => 'ST-54B', 'plant' => 'B'],
            ['nama_mesin' => 'ST-54D', 'plant' => 'B'],
            ['nama_mesin' => 'AR-72', 'plant' => 'B'],
            ['nama_mesin' => 'WR-1', 'plant' => 'B'],
            ['nama_mesin' => 'Heli 1,8 Ton', 'plant' => 'B'],
            ['nama_mesin' => 'Nissan 3,5 Ton', 'plant' => 'B'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'B'],

            // PLANT C
            ['nama_mesin' => 'MD-2C', 'plant' => 'C'],
            ['nama_mesin' => 'MD-3C', 'plant' => 'C'],
            ['nama_mesin' => 'TW-MD', 'plant' => 'C'],
            ['nama_mesin' => 'FD-9', 'plant' => 'C'],
            ['nama_mesin' => 'FD-10', 'plant' => 'C'],
            ['nama_mesin' => 'FD-11', 'plant' => 'C'],
            ['nama_mesin' => 'FD-12', 'plant' => 'C'],
            ['nama_mesin' => 'FD-20', 'plant' => 'C'],
            ['nama_mesin' => 'FD-21', 'plant' => 'C'],
            ['nama_mesin' => 'TIN-1', 'plant' => 'C'],
            ['nama_mesin' => 'TIN-2', 'plant' => 'C'],
            ['nama_mesin' => 'TIN-3', 'plant' => 'C'],
            ['nama_mesin' => 'ELECTRO PLATING', 'plant' => 'C'],
            ['nama_mesin' => 'BC-1C', 'plant' => 'C'],
            ['nama_mesin' => 'BC-2C', 'plant' => 'C'],
            ['nama_mesin' => 'BC-3C', 'plant' => 'C'],
            ['nama_mesin' => 'BC-4C', 'plant' => 'C'],
            ['nama_mesin' => 'BC-5C', 'plant' => 'C'],
            ['nama_mesin' => 'BC-7', 'plant' => 'C'],
            ['nama_mesin' => 'BC-8', 'plant' => 'C'],
            ['nama_mesin' => 'BC-9', 'plant' => 'C'],
            ['nama_mesin' => 'BC-10', 'plant' => 'C'],
            ['nama_mesin' => 'TV-5', 'plant' => 'C'],
            ['nama_mesin' => 'TV-6', 'plant' => 'C'],
            ['nama_mesin' => 'TV-7', 'plant' => 'C'],
            ['nama_mesin' => 'TV-8', 'plant' => 'C'],
            ['nama_mesin' => 'TV-9', 'plant' => 'C'],
            ['nama_mesin' => 'TV-10', 'plant' => 'C'],
            ['nama_mesin' => 'TV-11', 'plant' => 'C'],
            ['nama_mesin' => 'TV-12', 'plant' => 'C'],
            ['nama_mesin' => 'EX-65 1C', 'plant' => 'C'],
            ['nama_mesin' => 'EX-65 2C', 'plant' => 'C'],
            ['nama_mesin' => 'EX-80+50 A', 'plant' => 'C'],
            ['nama_mesin' => 'EX-80+50 B', 'plant' => 'C'],
            ['nama_mesin' => 'EX-65 3C', 'plant' => 'C'],
            ['nama_mesin' => 'EX-65 4C', 'plant' => 'C'],
            ['nama_mesin' => 'TW-630 A', 'plant' => 'C'],
            ['nama_mesin' => 'TW-630 B', 'plant' => 'C'],
            ['nama_mesin' => 'TW-800A', 'plant' => 'C'],
            ['nama_mesin' => 'TW-800B', 'plant' => 'C'],
            ['nama_mesin' => 'TW-125A', 'plant' => 'C'],
            ['nama_mesin' => 'TW-125B', 'plant' => 'C'],
            ['nama_mesin' => 'CB-16A', 'plant' => 'C'],
            ['nama_mesin' => 'CB-16C', 'plant' => 'C'],
            ['nama_mesin' => 'CB-20A', 'plant' => 'C'],
            ['nama_mesin' => 'EX-80J', 'plant' => 'C'],
            ['nama_mesin' => 'EX-90E', 'plant' => 'C'],
            ['nama_mesin' => 'EX-120F', 'plant' => 'C'],
            ['nama_mesin' => 'EX-150C', 'plant' => 'C'],
            ['nama_mesin' => 'EX-120A', 'plant' => 'C'],
            ['nama_mesin' => 'EX-120/100D', 'plant' => 'C'],
            ['nama_mesin' => 'ST-12A', 'plant' => 'C'],
            ['nama_mesin' => 'REW-TWB-16', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-16A', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-16B', 'plant' => 'C'],
            ['nama_mesin' => 'REW-TWB-24A', 'plant' => 'C'],
            ['nama_mesin' => 'REW-TWB-24B', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-24A', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-24B', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-24C', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-24D', 'plant' => 'C'],
            ['nama_mesin' => 'TWB-24E', 'plant' => 'C'],
            ['nama_mesin' => 'REW-SWB-24A', 'plant' => 'C'],
            ['nama_mesin' => 'REW-SWB-24B', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-24A', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-24B', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-24C', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-24D', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-24E', 'plant' => 'C'],
            ['nama_mesin' => 'REW-SWB-32A', 'plant' => 'C'],
            ['nama_mesin' => 'REW-SWB-32B', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-32A', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-32B', 'plant' => 'C'],
            ['nama_mesin' => 'REW-SWB-48A', 'plant' => 'C'],
            ['nama_mesin' => 'SWB-48', 'plant' => 'C'],
            ['nama_mesin' => 'TP-10', 'plant' => 'C'],
            ['nama_mesin' => 'Heli 2,5 Ton', 'plant' => 'C'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'C'],

            // PLANT D
            ['nama_mesin' => 'CCV-JHON ROYLE', 'plant' => 'D'],
            ['nama_mesin' => 'CCV-PAMPASS', 'plant' => 'D'],
            ['nama_mesin' => 'CCV-SUMITOMO', 'plant' => 'D'],
            ['nama_mesin' => 'REW-5', 'plant' => 'D'],
            ['nama_mesin' => 'REW-6', 'plant' => 'D'],
            ['nama_mesin' => 'REW-7', 'plant' => 'D'],
            ['nama_mesin' => 'TP-5', 'plant' => 'D'],
            ['nama_mesin' => 'TP-6', 'plant' => 'D'],
            ['nama_mesin' => 'TP-8', 'plant' => 'D'],
            ['nama_mesin' => 'TP-2', 'plant' => 'D'],
            ['nama_mesin' => 'TP-11', 'plant' => 'D'],
            ['nama_mesin' => 'TP-1', 'plant' => 'D'],
            ['nama_mesin' => 'TP-3', 'plant' => 'D'],
            ['nama_mesin' => 'TP-4', 'plant' => 'D'],
            ['nama_mesin' => 'EX--100A', 'plant' => 'D'],
            ['nama_mesin' => 'CB-26A', 'plant' => 'D'],
            ['nama_mesin' => 'CB-26B', 'plant' => 'D'],
            ['nama_mesin' => 'EX--100C', 'plant' => 'D'],
            ['nama_mesin' => 'EX--120B', 'plant' => 'D'],
            ['nama_mesin' => 'EX--120C', 'plant' => 'D'],
            ['nama_mesin' => 'EX--160A', 'plant' => 'D'],
            ['nama_mesin' => 'TP-7', 'plant' => 'D'],
            ['nama_mesin' => 'Heli 10 Ton', 'plant' => 'D'],
            ['nama_mesin' => 'Heli 2,5 Ton', 'plant' => 'D'],

            // PLANT E
            ['nama_mesin' => 'COL-4A', 'plant' => 'E'],
            ['nama_mesin' => 'COL-4B', 'plant' => 'E'],
            ['nama_mesin' => 'COL-9F', 'plant' => 'E'],
            ['nama_mesin' => 'COL-5F', 'plant' => 'E'],
            ['nama_mesin' => 'COL-8F A', 'plant' => 'E'],
            ['nama_mesin' => 'COL-8F B', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-7F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-8F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-9F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-10F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-11F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-12F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-13F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-14F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-15F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-16F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-45-17F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-30F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-50F', 'plant' => 'E'],
            ['nama_mesin' => 'PATH CORD', 'plant' => 'E'],
            ['nama_mesin' => 'PIG TAILD', 'plant' => 'E'],
            ['nama_mesin' => 'DC-1', 'plant' => 'E'],
            ['nama_mesin' => 'DC-2', 'plant' => 'E'],
            ['nama_mesin' => 'DC-3', 'plant' => 'E'],
            ['nama_mesin' => 'CB-4F', 'plant' => 'E'],
            ['nama_mesin' => 'CB-5F', 'plant' => 'E'],
            ['nama_mesin' => 'CB-6F', 'plant' => 'E'],
            ['nama_mesin' => 'CB-7F', 'plant' => 'E'],
            ['nama_mesin' => 'CB-8F', 'plant' => 'E'],
            ['nama_mesin' => 'CB-9F', 'plant' => 'E'],
            ['nama_mesin' => 'EX-90G', 'plant' => 'E'],
            ['nama_mesin' => 'EX-90H', 'plant' => 'E'],
            ['nama_mesin' => 'EX-90I', 'plant' => 'E'],
            ['nama_mesin' => 'EX-90J', 'plant' => 'E'],

            // OTHER PLANTS
            ['nama_mesin' => 'Heli 2,5 Ton', 'plant' => 'SC'],
            ['nama_mesin' => 'Nissan 2,5 Ton', 'plant' => 'SC'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'SC'],
            ['nama_mesin' => 'Nissan 3,5 Ton', 'plant' => 'SS'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'SS'],
            ['nama_mesin' => 'Heli 7 Ton', 'plant' => 'SS'],
            ['nama_mesin' => 'Heli 10 Ton', 'plant' => 'SS'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'FO'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'FH'],
            ['nama_mesin' => 'Heli 3,5 Ton', 'plant' => 'QR'],
        ];

        foreach ($mesins as $mesin) {
            Mesin::create($mesin);
        }

        // 3. Hidupkan kembali pengecekan foreign key
        Schema::enableForeignKeyConstraints();
    }
}